---
name: UV

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
  SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}

permissions:
  contents: read # Allows actions/checkout to read the repository contents.

jobs:
  uv:
    name: python
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        python-version:
          - "3.12"
          - "3.13"
          - "3.13t"
          - "3.14"
          - "3.14t"
        os:
          - "ubuntu-latest"
    steps:
      - name: Checkout
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10
        with:
          fetch-depth: 0
          persist-credentials: false
      - name: Install uv
        uses: astral-sh/setup-uv@fac544c07dec837d0ccb6301d7b5580bf5edae39
        with:
          python-version: ${{ matrix.python-version }}
      - name: Set PYTHON_GIL
        if: endsWith(matrix.python-version, 't')
        run: echo "PYTHON_GIL=0" >> "$GITHUB_ENV"
      - name: Set up Python
        run: uv python install
      - name: pyTest
        run: uv run pytest tests
      - name: Ruff (check)
        run: uv run ruff check
      - name: Ruff (format)
        run: uv run ruff format --diff --check
      - name: Ty
        run: uv run ty check
      - name: Troml
        run: uv run troml check
      - name: pip-audit
        run: uv run --with pip-audit pip-audit --strict
  sonarqube:
    name: sonarqube
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        python-version:
          - "3.12"
        os:
          - "ubuntu-latest"
    steps:
      - name: Checkout
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10
        with:
          fetch-depth: 0
          persist-credentials: false
      - name: Run SonarQube
        uses: sonarsource/sonarqube-scan-action@7006c4492b2e0ee0f816d36501671557c97f5995
        env:
          SONAR_TOKEN: ${{ env.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ env.SONAR_HOST_URL }}
