---
name: Zizmor

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions: {}

jobs:
  zizmor:
    name: Zizmor
    runs-on: ubuntu-latest
    permissions:
      security-events: write # Allows zizmor to write security events.
      contents: read # Required for private repositories.
      actions: read # Required for private repositories.
    steps:
      - name: Checkout repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd
        with:
          persist-credentials: false
      - name: Run zizmor 🌈
        uses: zizmorcore/zizmor-action@b1d7e1fb5de872772f31590499237e7cce841e8e
        with:
          inputs: |
            .github/*.yml
            .github/workflows/*.yml
